### ISSUE TITLE
Not working on Windows XP SP3

### ISSUE THREAD

**Issue by zouharvi** [Jirka-Mayer/CoolKey#1]
Tried to run CoolKey on my Windows XP SP3, but I couldn't even launch it by double clicking the executable on desktop - it's missing completely!

Please fix.

**Comment by Jirka-Mayer** [comment]
It desn't work on Ubuntu 18.04 either! This code is total garbage, I seriously doubt the author's mental health while sharing it on github.

**Comment by zouharvi** [comment]
Yes.
